/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BackgroundWork.koneksi;
import Objek.Pasien;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dimas Adiyaksa
 */
public class detailPas extends javax.swing.JFrame {

    /**
     * Creates new form detailPas
     */
    Pasien p = new Pasien();
    koneksi kon = new koneksi();
    
    public detailPas() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public detailPas(Pasien p) {
        initComponents();
        setLocationRelativeTo(null);
        this.p = p;
        alamatLabel.setEditable(false);
        inisiasi();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void inisiasi(){
        ResultSet ruang = null;
        ResultSet penyakit = null;
        String r = null;
        String pe = null;
        String dtIn = null;
        String dtOut = null;
        
        kodeLabel.setText(p.getId());
        namaLabel.setText(p.getNama());
        if(p.getJenis_kelamin().equals("L")){
            jkLabel.setText("Laki-laki");
        }else{
            jkLabel.setText("Perempuan");
        }
        
            
        
        umurLabel.setText(Integer.toString(p.getUmur()));
        alamatLabel.setText(p.getAlamat());
        ruangLabel.setText(p.getKodeRuang());
        penyakitLabel.setText(p.getKodePenyakit());
        
        
        
            
   //     System.out.println(dtIn);
        setPegawai();
        tglInMasuk.setText(parseIn(p));
        tglOutLabel.setText(parseOut(p));
        
    }
    
    public String parseIn(Pasien p){
        String dtIn;
        dtIn = Character.toString(p.getIn().charAt(8))+
                Character.toString(p.getIn().charAt(9))+
                Character.toString(p.getIn().charAt(7))+
                Character.toString(p.getIn().charAt(5))+
                Character.toString(p.getIn().charAt(6))+
                Character.toString(p.getIn().charAt(4))+
                Character.toString(p.getIn().charAt(0))+
                Character.toString(p.getIn().charAt(1))+
                Character.toString(p.getIn().charAt(2))+
                Character.toString(p.getIn().charAt(3));
        return dtIn;
    }
    
    public String parseOut(Pasien p){
        String dtOut;
        dtOut = Character.toString(p.getOut().charAt(8))+
                Character.toString(p.getOut().charAt(9))+
                Character.toString(p.getOut().charAt(7))+
                Character.toString(p.getOut().charAt(5))+
                Character.toString(p.getOut().charAt(6))+
                Character.toString(p.getOut().charAt(4))+
                Character.toString(p.getOut().charAt(0))+
                Character.toString(p.getOut().charAt(1))+
                Character.toString(p.getOut().charAt(2))+
                Character.toString(p.getOut().charAt(3));
        return dtOut;
    }
    
    public void setPegawai(){
        ResultSet peg = null;
        String dokter = null;
        String perawat = null;
        
        try {
            peg = kon.koneksikan("SELECT kepegawaian.Nama, kepegawaian.Profesi FROM `kepegawaian` INNER JOIN " +
                    "perawatan ON NIP = perawatan.`Kode Dokter` " +
                    "OR NIP = perawatan.`Kode Perawat` " +
                    "INNER JOIN pasien ON perawatan.`Kode Pasien` = '"+p.getId()+"'");
            
            while(peg.next()){
                if(peg.getString("profesi").equals("Dokter")){
                    dokter = peg.getString("Nama");
                }else{
                    perawat = peg.getString("Nama");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(detailPas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        dok.setText(p.getDokterName());
        per.setText(p.getPerawatName());
        
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tutupButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatLabel = new javax.swing.JTextArea();
        kodeLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        umurLabel = new javax.swing.JLabel();
        jkLabel = new javax.swing.JLabel();
        ruangLabel = new javax.swing.JLabel();
        penyakitLabel = new javax.swing.JLabel();
        tglInMasuk = new javax.swing.JLabel();
        tglOutLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dok = new javax.swing.JLabel();
        per = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(429, 552));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Kode                 :");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Nama                :");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Jenis Kelamin    :");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Umur                  :");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setText("Alamat              : ");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Ruang                :");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setText("Penyakit            :");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setText("Tanggal Masuk :");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setText("Tanggal Keluar :");

        tutupButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tutupButton.setText("Tutup");
        tutupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutupButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        alamatLabel.setColumns(20);
        alamatLabel.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        alamatLabel.setLineWrap(true);
        alamatLabel.setRows(5);
        alamatLabel.setOpaque(false);
        jScrollPane1.setViewportView(alamatLabel);

        kodeLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        kodeLabel.setText("jLabel10");

        namaLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        namaLabel.setText("jLabel11");

        umurLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        umurLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        umurLabel.setText("jLabel12");

        jkLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jkLabel.setText("jLabel13");

        ruangLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        ruangLabel.setText("jLabel14");

        penyakitLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        penyakitLabel.setText("jLabel15");

        tglInMasuk.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tglInMasuk.setText("jLabel16");

        tglOutLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tglOutLabel.setText("jLabel17");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setText("DETAIL PASIEN");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setText("Dokter                :");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setText("Perawat             :");

        dok.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        dok.setText("jLabel13");

        per.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        per.setText("jLabel14");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(per))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dok)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(penyakitLabel))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tglInMasuk))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tglOutLabel))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ruangLabel))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(kodeLabel))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(namaLabel))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jkLabel))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(umurLabel))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(tutupButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jkLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(umurLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ruangLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(penyakitLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(dok))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(per))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tglInMasuk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tglOutLabel))
                .addGap(3, 3, 3)
                .addComponent(tutupButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tutupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutupButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_tutupButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detailPas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detailPas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detailPas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detailPas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detailPas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatLabel;
    private javax.swing.JLabel dok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jkLabel;
    private javax.swing.JLabel kodeLabel;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel penyakitLabel;
    private javax.swing.JLabel per;
    private javax.swing.JLabel ruangLabel;
    private javax.swing.JLabel tglInMasuk;
    private javax.swing.JLabel tglOutLabel;
    private javax.swing.JButton tutupButton;
    private javax.swing.JLabel umurLabel;
    // End of variables declaration//GEN-END:variables
}
