/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BackgroundWork.List;
import BackgroundWork.koneksi;
import Objek.Pasien;
import Objek.ruangan;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dimas Adiyaksa
 */
public class ruangDet extends javax.swing.JFrame {

    /**
     * Creates new form ruangDet
     */
    ruangan r = new ruangan();
 //   Pasien p = new Pasien();
    koneksi kon = new koneksi();
    public ruangDet() {
        initComponents();
    }

    public ruangDet(ruangan r){
        initComponents();
        this.r = r;
         setLocationRelativeTo(null);
         table.setDefaultEditor(Object.class,null);
         inisiasi();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void inisiasi(){
        kd.setText(r.getKodeRuang());
        nm.setText(r.getNamaRuang());
        jns.setText(r.getJenisRuang());
        loadTable();
        jml.setText(Integer.toString(table.getRowCount()));
    }
    
    public void loadTable(){
        DefaultTableModel model = new DefaultTableModel();
        ResultSet rs = null;
        model = new DefaultTableModel(null,new String[]{
            "Nomor","Pasien","Penyakit","Tanggal Masuk","Tanggal Keluar"
        });
        Object row[] = new Object[5];
        int no=1;
        try {
            rs = kon.koneksikan("SELECT pasien.Nama,`info penyakit`.`Nama Penyakit`,"
                    + "`penempatan`.`Tanggal Masuk`,`penempatan`.`Tanggal Keluar` FROM pasien \n" +
                    "INNER JOIN `info penyakit` ON  `info penyakit`.`Kode Penyakit` = `pasien`.`Kode Penyakit`\n" +
                    "INNER JOIN penempatan ON `penempatan`.`Kode Pasien` = `pasien`.`Kode Pasien`\n" +
                    "AND `pasien`.`Kode Ruang` = '"+kd.getText()+"'");
            while(rs.next()){
                row[0] = no;
                row[1] = rs.getString("Nama");
                row[2] = rs.getString("Nama Penyakit");
                row[3] = parseIn(rs.getString("Tanggal Masuk"));
                row[4] = parseOut(rs.getString("Tanggal Keluar"));
                model.addRow(row);
                no++;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ruangDet.class.getName()).log(Level.SEVERE, null, ex);
        }
        table.setModel(model);
        
    }
    
    public String parseIn(String s){
        String dtIn;
        dtIn = Character.toString(s.charAt(8))+
                Character.toString(s.charAt(9))+
                Character.toString(s.charAt(7))+
                Character.toString(s.charAt(5))+
                Character.toString(s.charAt(6))+
                Character.toString(s.charAt(4))+
                Character.toString(s.charAt(0))+
                Character.toString(s.charAt(1))+
                Character.toString(s.charAt(2))+
                Character.toString(s.charAt(3));
        return dtIn;
    }
    
    public String parseOut(String s){
        String dtOut;
        dtOut = Character.toString(s.charAt(8))+
                Character.toString(s.charAt(9))+
                Character.toString(s.charAt(7))+
                Character.toString(s.charAt(5))+
                Character.toString(s.charAt(6))+
                Character.toString(s.charAt(4))+
                Character.toString(s.charAt(0))+
                Character.toString(s.charAt(1))+
                Character.toString(s.charAt(2))+
                Character.toString(s.charAt(3));
        return dtOut;
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        kd = new javax.swing.JLabel();
        nm = new javax.swing.JLabel();
        jns = new javax.swing.JLabel();
        jml = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("DETAIL RUANG");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Kode   :");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Nama  :");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Jenis    :");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setText("Jumlah Pasien :");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Pasien", "Penyakit", "Tanggal Masuk", "Tanggal Keluar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table.getTableHeader().setResizingAllowed(false);
        jScrollPane1.setViewportView(table);

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton1.setText("Tutup");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        kd.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        kd.setText("jLabel6");

        nm.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        nm.setText("jLabel7");

        jns.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jns.setText("jLabel8");

        jml.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jml.setText("jLabel9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nm))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jns))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jml))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kd)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(kd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jns))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jml))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ruangDet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ruangDet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ruangDet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ruangDet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ruangDet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jml;
    private javax.swing.JLabel jns;
    private javax.swing.JLabel kd;
    private javax.swing.JLabel nm;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
