/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BackgroundWork.List;
import BackgroundWork.TambahPasien;
import BackgroundWork.TambahPeg;
import Objek.Pasien;
import Objek.Pegawai;
import Objek.ruangan;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dimas Adiyaksa
 */
public class Tambah extends javax.swing.JFrame {

    /**
     * Creates new form Tambah
     */
    TambahPasien tPas = new TambahPasien();
    
    private List psn = new List();
    private List peg = new List();
    private List ruang = new List();
    private List peny = new List();
    private Pasien p = new Pasien();
    
    public Tambah(){
        
    };
    
    public Tambah(List psn,List peg,List ruang,List peny) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.psn = psn;
        this.peg = peg;
        this.ruang = ruang;
        this.peny = peny;
        try {
            showKode.setText(tPas.getKdPas());
        } catch (SQLException ex) {
            Logger.getLogger(Tambah.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        tPas.PenyakitPasien(penyBx);
        
        tPas.ruangBox(ruangBox);
        tPas.dokterBox(dokterBox);
        tPas.perawatBox(perawatBox);
        
        try {
            tPas.setPenyakitLabel(penyBx, kodePenyPas, kategoriPenyPas);
        } catch (SQLException ex) {
            Logger.getLogger(Tambah.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        tambah = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        kdPasien = new javax.swing.JLabel();
        showKode = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        umurLabel = new javax.swing.JLabel();
        umurField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JKBox = new javax.swing.JComboBox<>();
        alamatLabel = new javax.swing.JLabel();
        spAlamat = new javax.swing.JScrollPane();
        alamatField = new javax.swing.JTextArea();
        ruangLabel = new javax.swing.JLabel();
        ruangBox = new javax.swing.JComboBox<>();
        penyakitLabel = new javax.swing.JLabel();
        kdPenyakitLabel = new javax.swing.JLabel();
        kategoriPenyakitLabel = new javax.swing.JLabel();
        perawatLabel = new javax.swing.JLabel();
        dokterLabel = new javax.swing.JLabel();
        dokterBox = new javax.swing.JComboBox<>();
        perawatBox = new javax.swing.JComboBox<>();
        tglIn = new org.jdesktop.swingx.JXDatePicker();
        tglOut = new org.jdesktop.swingx.JXDatePicker();
        tglMasuk = new javax.swing.JLabel();
        tglKeluar = new javax.swing.JLabel();
        penyBx = new javax.swing.JComboBox<>();
        kodePenyPas = new javax.swing.JLabel();
        kategoriPenyPas = new javax.swing.JLabel();
        batal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        nip = new javax.swing.JTextField();
        NIP = new javax.swing.JLabel();
        nmPeg = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        jk = new javax.swing.JLabel();
        profesi = new javax.swing.JLabel();
        ket = new javax.swing.JLabel();
        namaPeg = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatPeg = new javax.swing.JTextArea();
        jkboxpeg = new javax.swing.JComboBox<>();
        profesiBox = new javax.swing.JComboBox<>();
        kett = new javax.swing.JTextField();
        tambahPeg = new javax.swing.JButton();
        batalPeg = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tambahPenyakit = new javax.swing.JButton();
        kdPenyakit = new javax.swing.JTextField();
        namaPenyakit = new javax.swing.JTextField();
        CBoxKatePenyakit = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kdRuang = new javax.swing.JTextField();
        namaRuang = new javax.swing.JTextField();
        jenisRuangBox = new javax.swing.JComboBox<>();
        tambahRuang = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        kdPasien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kdPasien.setText("Kode Pasien    :");

        showKode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        namaLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namaLabel.setText("Nama Pasien   :");

        namaField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaFieldActionPerformed(evt);
            }
        });

        umurLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        umurLabel.setText("Umur              :");

        umurField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        umurField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Jenis Kelamin   :");

        JKBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perempuan", "Laki-Laki" }));

        alamatLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alamatLabel.setText("Alamat            :");

        spAlamat.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        alamatField.setColumns(20);
        alamatField.setRows(5);
        spAlamat.setViewportView(alamatField);

        ruangLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ruangLabel.setText("Ruangan        :");

        ruangBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        penyakitLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        penyakitLabel.setText("Penyakit        : ");

        kdPenyakitLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kdPenyakitLabel.setText("Kode       : ");

        kategoriPenyakitLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kategoriPenyakitLabel.setText("Kategori  : ");

        perawatLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        perawatLabel.setText("Perawat         : ");

        dokterLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dokterLabel.setText("Dokter           :");

        dokterBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        perawatBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tglMasuk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tglMasuk.setText("Tgl Masuk      :");

        tglKeluar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tglKeluar.setText("Tgl Keluar      :");

        penyBx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        penyBx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                penyBxItemStateChanged(evt);
            }
        });

        kodePenyPas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kodePenyPas.setText(" ");

        kategoriPenyPas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kategoriPenyPas.setText(" ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kdPasien)
                            .addComponent(namaLabel)
                            .addComponent(umurLabel)
                            .addComponent(jLabel5)
                            .addComponent(alamatLabel)
                            .addComponent(ruangLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ruangBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(namaField)
                                .addComponent(umurField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JKBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(showKode, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(penyakitLabel)
                            .addComponent(dokterLabel)
                            .addComponent(perawatLabel)
                            .addComponent(tglMasuk)
                            .addComponent(tglKeluar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(penyBx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tglOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(kdPenyakitLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(kodePenyPas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(tglIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(perawatBox, 0, 129, Short.MAX_VALUE)
                                    .addComponent(dokterBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(kategoriPenyakitLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kategoriPenyPas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kdPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showKode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(umurLabel)
                    .addComponent(umurField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JKBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamatLabel)
                    .addComponent(spAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruangLabel)
                    .addComponent(ruangBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(penyakitLabel)
                    .addComponent(penyBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kdPenyakitLabel)
                    .addComponent(kodePenyPas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kategoriPenyakitLabel)
                    .addComponent(kategoriPenyPas))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dokterLabel)
                    .addComponent(dokterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perawatLabel)
                    .addComponent(perawatBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglMasuk))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglKeluar))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel4);

        batal.setText("Batal");
        batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tambah)
                .addGap(17, 17, 17)
                .addComponent(batal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah)
                    .addComponent(batal)))
        );

        jTabbedPane1.addTab("Pasien", jPanel3);

        nip.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nip.setText(" ");
        nip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nipActionPerformed(evt);
            }
        });

        NIP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NIP.setText("NIP                :");

        nmPeg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nmPeg.setText("Nama             :");

        alamat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alamat.setText("Alamat            :");

        jk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jk.setText("Jenis Kelamin  : ");

        profesi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        profesi.setText("Profesi            :");

        ket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ket.setText("Keterangan    :");

        namaPeg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namaPeg.setText(" ");

        alamatPeg.setColumns(20);
        alamatPeg.setRows(5);
        jScrollPane1.setViewportView(alamatPeg);

        jkboxpeg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));

        profesiBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dokter", "Perawat", " " }));

        kett.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kett.setText(" ");

        tambahPeg.setText("Tambah");
        tambahPeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPegActionPerformed(evt);
            }
        });

        batalPeg.setText("Batal");
        batalPeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalPegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NIP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nip, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nmPeg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(namaPeg))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(alamat)
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jkboxpeg, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ket)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kett))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(profesi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(profesiBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tambahPeg)
                        .addGap(18, 18, 18)
                        .addComponent(batalPeg))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIP))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nmPeg)
                    .addComponent(namaPeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamat)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jk)
                    .addComponent(jkboxpeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profesiBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profesi))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ket)
                    .addComponent(kett, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahPeg)
                    .addComponent(batalPeg)))
        );

        jTabbedPane1.addTab("Pegawai", jPanel1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Kode Penyakit  :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama Penyakit :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Kategori           :");

        tambahPenyakit.setText("Tambah");
        tambahPenyakit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahPenyakitMouseClicked(evt);
            }
        });

        kdPenyakit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        namaPenyakit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        CBoxKatePenyakit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ringan", "Menengah", "Berat" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Kode Ruang    :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nama Ruang   :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Jenis Ruang    :");

        kdRuang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        namaRuang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jenisRuangBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reguler", "VIP" }));

        tambahRuang.setText("Tambah");
        tambahRuang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahRuangActionPerformed(evt);
            }
        });

        jButton1.setText("Batal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kdPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namaPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CBoxKatePenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kdRuang, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(namaRuang))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jenisRuangBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 60, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tambahPenyakit)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tambahRuang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kdPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CBoxKatePenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(tambahPenyakit)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kdRuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(namaRuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jenisRuangBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahRuang)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ruang dan Penyakit", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Pasien");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nipActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        String kdRuang = null;
        String kdPenyakit;
        String jk;
        String j;
        String kdper = null;
        
        try {
            kdper = tPas.getKdPer();
        } catch (SQLException ex) {
            Logger.getLogger(Tambah.class.getName()).log(Level.SEVERE, null, ex);
        }              
        
        char a;
        int umur;
        jk = (String) JKBox.getSelectedItem();
        a = jk.charAt(0);
        j = Character.toString(a);
        try {
            kdRuang = tPas.getKdRuang(ruangBox);

        } catch (SQLException ex) {
            Logger.getLogger(Tambah.class.getName()).log(Level.SEVERE, null, ex);
        }
        umur = Integer.parseInt(umurField.getText());
        String sql = null;
        
        
        sql = "INSERT INTO `pasien`"+"VALUES('"+
                showKode.getText()+"','"+namaField.getText()+
                "',"+umur+",'"+a+"','"+alamatField.getText()+"','"+
                kdper+"','"+kdRuang+"','"+kodePenyPas.getText()+"')";
        
        String in = null;
        String out;
        
        DateFormat dtform = new SimpleDateFormat("yyyy-MM-dd");
        in = dtform.format(tglIn.getDate());
        out = dtform.format(tglOut.getDate());
        
        
        try {
            tPas.insert(sql);
            tPas.setPerawatan(tglIn, tglOut,(String)dokterBox.getSelectedItem(),(String)perawatBox.getSelectedItem(),
                    showKode.getText(),kdRuang,kdper);
            //JOptionPane.showMessageDialog(null, "Berhasil!");
            ArrayList<Pasien> x = new ArrayList();
            
            x = psn.getList();
            p = new Pasien(showKode.getText(),namaField.getText(),j,alamatField.getText(),
            umur,tPas.getKdPer(),ruangBox.getSelectedItem().toString(),penyBx.getSelectedItem().toString(),
                    in,out);
            
            p.setDokterName(dokterBox.getSelectedItem().toString());
            p.setPerawatName(perawatBox.getSelectedItem().toString());
            x.add(p);
           JOptionPane.showMessageDialog(null, "Input Berhasil");
            dispose();
            showKode.setText(tPas.getKdPas());
            flushPas();
        } catch (SQLException ex) {
            Logger.getLogger(Tambah.class.getName()).log(Level.SEVERE, null, ex);
           // JOptionPane.showMessageDialog(null, "Gagal\n"+ex);
        }
        
    }//GEN-LAST:event_tambahActionPerformed

    private void penyBxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_penyBxItemStateChanged
        try {
            // TODO add your handling code here:
            tPas.setPenyakitLabel(penyBx,kodePenyPas , kategoriPenyPas);
        } catch (SQLException ex) {
            Logger.getLogger(Tambah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_penyBxItemStateChanged

    private void namaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaFieldActionPerformed

    private void batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batalMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_batalMouseClicked

    private void tambahPegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPegActionPerformed
        // TODO add your handling code here:
        TambahPeg tp = new TambahPeg();
        char jk = jkboxpeg.getSelectedItem().toString().charAt(0);
        Pegawai p = new Pegawai();
        
        String sql = "INSERT INTO `kepegawaian` VALUES ('"+nip.getText()+"','"+namaPeg.getText()+"','"+
                alamatPeg.getText()+"','"+jk+"','"+
                profesiBox.getSelectedItem().toString()+"','"+kett.getText()+"')";
        p.setId(nip.getText());
        p.setAlamat(alamatPeg.getText());
        p.setJenis_kelamin(Character.toString(jk));
        p.setKeterangan(kett.getText());
        p.setNama(namaPeg.getText());
        p.setProfesi(profesiBox.getSelectedItem().toString());
        peg.getListPeg().add(p);
        JOptionPane.showMessageDialog(null, "Input Berhasil");
        dispose();
        tp.tambah(sql);
        
    }//GEN-LAST:event_tambahPegActionPerformed

    private void batalPegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalPegActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_batalPegActionPerformed

    private void tambahPenyakitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahPenyakitMouseClicked
        // TODO add your handling code here:
        String sql = null;
        if(!kdPenyakit.equals("")&&!namaPenyakit.equals("")){
            sql="INSERT INTO `info penyakit` VALUES "
                    + "('"+kdPenyakit.getText()+"','"+namaPenyakit.getText()+"','"
                    + CBoxKatePenyakit.getSelectedItem().toString()+"')";
        }
        
        tPas.insert(sql);
        JOptionPane.showMessageDialog(null,"Berhasil");
        dispose();
        
    }//GEN-LAST:event_tambahPenyakitMouseClicked

    private void tambahRuangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahRuangActionPerformed
        // TODO add your handling code here:
        String sql = null;
        ruangan r = new ruangan();
        ArrayList<ruangan> x;
        x = new ArrayList();
        if(!kdPenyakit.equals("")&&!namaPenyakit.equals("")){
            sql="INSERT INTO `ruangan` VALUES "
                    + "('"+kdRuang.getText()+"','"+namaRuang.getText()+"','"
                    + jenisRuangBox.getSelectedItem().toString()+"')";
            r.setJenisRuang(jenisRuangBox.getSelectedItem().toString());
            r.setKodeRuang(kdRuang.getText());
            r.setNamaRuang(namaRuang.getText());
        }else{
            JOptionPane.showMessageDialog(null, "Lengkapi Data!");
        }
        
        ruang.getListRuang().add(r);
        
        tPas.insert(sql);
        JOptionPane.showMessageDialog(null,"Berhasil");
        dispose();
    }//GEN-LAST:event_tambahRuangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void flushPas() throws SQLException{
        namaField.setText("");
        alamatField.setText("");
        umurField.setText("");
        tglIn.setDate(null);
        tglOut.setDate(null);
      
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tambah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBoxKatePenyakit;
    private javax.swing.JComboBox<String> JKBox;
    private javax.swing.JLabel NIP;
    private javax.swing.JLabel alamat;
    private javax.swing.JTextArea alamatField;
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JTextArea alamatPeg;
    private javax.swing.JButton batal;
    private javax.swing.JButton batalPeg;
    private javax.swing.JComboBox<String> dokterBox;
    private javax.swing.JLabel dokterLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jenisRuangBox;
    private javax.swing.JLabel jk;
    private javax.swing.JComboBox<String> jkboxpeg;
    private javax.swing.JLabel kategoriPenyPas;
    private javax.swing.JLabel kategoriPenyakitLabel;
    private javax.swing.JLabel kdPasien;
    private javax.swing.JTextField kdPenyakit;
    private javax.swing.JLabel kdPenyakitLabel;
    private javax.swing.JTextField kdRuang;
    private javax.swing.JLabel ket;
    private javax.swing.JTextField kett;
    private javax.swing.JLabel kodePenyPas;
    private javax.swing.JTextField namaField;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField namaPeg;
    private javax.swing.JTextField namaPenyakit;
    private javax.swing.JTextField namaRuang;
    private javax.swing.JTextField nip;
    private javax.swing.JLabel nmPeg;
    private javax.swing.JComboBox<String> penyBx;
    private javax.swing.JLabel penyakitLabel;
    private javax.swing.JComboBox<String> perawatBox;
    private javax.swing.JLabel perawatLabel;
    private javax.swing.JLabel profesi;
    private javax.swing.JComboBox<String> profesiBox;
    private javax.swing.JComboBox<String> ruangBox;
    private javax.swing.JLabel ruangLabel;
    private javax.swing.JLabel showKode;
    private javax.swing.JScrollPane spAlamat;
    private javax.swing.JButton tambah;
    private javax.swing.JButton tambahPeg;
    private javax.swing.JButton tambahPenyakit;
    private javax.swing.JButton tambahRuang;
    private org.jdesktop.swingx.JXDatePicker tglIn;
    private javax.swing.JLabel tglKeluar;
    private javax.swing.JLabel tglMasuk;
    private org.jdesktop.swingx.JXDatePicker tglOut;
    private javax.swing.JTextField umurField;
    private javax.swing.JLabel umurLabel;
    // End of variables declaration//GEN-END:variables
}
